### ISSUE TITLE
Feature request: possibility to debug into macro when running Batch+

### ISSUE THREAD

**Issue by EddyAlleman** [xarial/cad-plus#101]
We can debug our macro when our solidworks files is open and just run the macro.

This means that the API takes into account that manually files where opened.
If we open files through code some Solidworks settings are not change like the working directory.

So testing in the Batch+ environment, would find those issues.

Remark: it is possible to use  MsgBox in your code and use the "Silent" setting:
![image](https://user-images.githubusercontent.com/979361/129562341-f5a91ab7-930d-4281-97f8-3b65bddb75f7.png)

Which will show the messages, but closes them automatically

Journal still shows them nevertheless:
![image](https://user-images.githubusercontent.com/979361/129562320-23cf7f75-ab0e-4a98-97b5-4bdd3ae054f1.png)

**Comment by artem1t** [comment]
You can add the following line in your macro and it will break so you can debug your macro as normal.

~~~ vb
Debug.Assert False
~~~

I have added the 'Documentation label so it will be added to the docs

**Comment by EddyAlleman** [comment]
Thanks a lot Artem

Works great!
