### ISSUE TITLE
Add a counter for number of files processed, like 105 out of 355.

### ISSUE THREAD

**Issue by alinvargatu** [xarial/cad-plus#40]
The progress bar is good, but would be nice to know exactly how many files are left for processing.
![image](https://user-images.githubusercontent.com/73069671/96372762-742dd900-1136-11eb-836f-d798c1be22e3.png)

**Comment by artem1t** [comment]
This information is displayed in the progress bar and summary card:

![image](https://user-images.githubusercontent.com/44194903/97106549-84395000-1716-11eb-8e2a-f0b192cd9e73.png)
