### ISSUE TITLE
Cad+ list of features shows missing symbol instead of 'v' mark on Android

### ISSUE THREAD

**Issue by EddyAlleman** [xarial/cad-plus#47]
Not directly related to the software but when visiting 
https://github.com/xarial and https://cadplus.xarial.com/ using Android:

In the table below:
> Please see the table below for the list of features and their availability in the specific editions.

We see rectangles with diagonals instead of the check mark. 
On windows 10 it is ok.

Eddy

**Comment by artem1t** [comment]
Thank you, Eddy. It has been fixed now in docs. The same was in iOS.
