### ISSUE TITLE
"New version is available" popup keeps appearing

### ISSUE THREAD

**Issue by EddyAlleman** [xarial/cad-plus#62]
The following popup keeps appearing
![image](https://user-images.githubusercontent.com/979361/99568309-8cac4000-29cf-11eb-91a8-940e4f911729.png)

But I have this test version installed:
0.5.1286.4
![image](https://user-images.githubusercontent.com/979361/99568517-cda45480-29cf-11eb-963b-b168bec6f1fa.png)

thanks,

Eddy

**Comment by artem1t** [comment]
Hi Eddie,

This popup will be shown when new production version is available. Please note that test package of the same version is upgradable to the production package of the same version as well as older production version is upgradabel to the newer production version. So in your case you can install the production version from here and the popup will go away: https://install.appcenter.ms/orgs/xarial/apps/cad-toolset/distribution_groups/production

Thanks,
Artem

**Comment by EddyAlleman** [comment]
Ok thanks for the clarification.

Eddy
