### ISSUE TITLE
Communicate the errors from macro and batch to the user

### ISSUE THREAD

**Issue by artem1t** [xarial/cad-plus#75]

**Comment by EwokNz** [comment]
Hi this would really help! I have the same issue. 

My macro sends a message box report. It is not showing when run through toolbar+. 
Cheers.

**Comment by artem1t** [comment]
For Batch+ Err.Raise and 'Silent' mode for the macro will register the error in the error box in the Summary table. See [Custom Errors](https://cadplus.xarial.com/batch/user-interface#custom-errors) for more information.

@EwokNz,  For Toolbar+ try MsgBox instead of SwApp.SendMsgToUser to display the message box
