### ISSUE TITLE
Trigger Macro on Open Document from within Assembly

### ISSUE THREAD

**Issue by 77Peter77** [xarial/cad-plus#84]
Hi Artem,
Small thing but could the trigger "Open Document" also run the macro when a sub-component is opened from within an active assembly? Maybe as an option?
I am running a small macro to set the FeatureManager Width to 300.

/Peter

**Comment by artem1t** [comment]
Hi Peter,

Thank you for the ticket. Try ActivateDocument trigger - this should be fired when the document is activated from the component

Regards,
Artem

**Comment by 77Peter77** [comment]
Thanks, Artem - it works great - I will close this Issue.

Regards,
Peter
